# Configuration file for KeywordLabeler GitHub App: https://github.com/marketplace/keywordlabeler

# Determines if we search the title (optional). Defaults to true.
matchTitle: true

# Determines if we search the body (optional). Defaults to true.
matchBody: true

# Explicit keyword mappings to labels. Form of match:label. Required.
labelMappings: []
