# Configuration file for Stale GitHub App: https://github.com/apps/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
- low-priority
- pinned
- security
- help-wanted

# Label to use when marking an issue as stale
staleLabel: stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs within
  seven days. If you believe this is a mistake, please reply to this comment
  to keep it open. If there isn't one already, a PR to fix or at least
  reproduce the problem in a test case will always help us get back on track
  to tackle this.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed due to inactivity. We apologise if
  this is still an active problem for you, and would ask you to re-open the
  issue if this is the case.
