# This file is handled by Dependabot and Renovate bots,
# so we'll run integration tests when a new Jaeger version is released
FROM jaegertracing/all-in-one:1.31.0@sha256:04d224a9999bbf9583e75d27af335bf7bcd870d2573f37218c9c0b1c9e38f3a0
