# This file is handled by Dependabot and Renovate bots,
# so we'll run integration tests when a new Jaeger version is released
FROM jaegertracing/all-in-one:1.29.0@sha256:42822be7888bb90ea359dcf14e3fd039ae8bfad08329691f6981796707c6d1dd
