# This file is handled by Dependabot and Renovate bots,
# so we'll run integration tests when a new Jaeger version is released
FROM jaegertracing/all-in-one:1.27.0@sha256:8d0bff43db3ce5c528cb6f957520511d263d7cceee012696e4afdc9087919bb9
