codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        enabled: yes
        target: 60%
        if_not_found: failure
    patch:
      default:
        enabled: yes
        target: 60%
        if_not_found: failure

comment:
  behavior: new
