os: linux
dist: bionic

language: java
jdk: openjdk8
install: skip

git:
  depth: 2

before_cache:
- rm -rf $HOME/.gradle/daemon $HOME/.gradle/build-scan-data $HOME/.gradle/kotlin-profile $HOME/.gradle/tmp $HOME/.gradle/workers
- find $HOME/.gradle -name '*.lock' -type f -delete

cache:
  directories:
  - $HOME/.gradle/

before_script:
- export GRADLE_OPTS="-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.warning.mode=all -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.io.useCanonCaches=false -Djava.awt.headless=true"
- sed -i 's/-all\.zip/-bin.zip/' gradle/wrapper/gradle-wrapper.properties

script:
- ./gradlew build

after_script:
- 'bash <(curl -s https://codecov.io/bash)'
