os: linux
dist: bionic

language: java
jdk: openjdk11
install: skip

addons:
  sonarcloud:
    organization: "remal"
    token:
      secure: 'N6bR6eG1kisxVLz2R/bMYZmY8fOUmskeYfUj5xnaAfNcuG5D+L2veSplUXwNPjslAiHsy/VfkYAFFcvhlfdm8qxaEdcFK1VyBl6o2NqbMokW+6ndjPWjYge4zGYQEcdOWGc5umLCwkBF+fZJ/XGKMGfbv3hXxK7JFzk2hQTzb2xQdXBa+rXK3AF/G9yAxtOn3lwXh5OrZYCWwyD9A7cU3CyLC256W1yrnUR65E44dvJqRIFycEI6TRmCTIhc7ZClj51VFrcbEqMR/ra1WFA5HEj7rFZ4bK9ZD4soZ45Msuti7Epo1o6q5yY+kZn7MmCz6fz4g2CnC6EpDWuNP7+mEjl5GYbrnoQ6SvTsD4Pfvsygfl10J/GsJobAcLJXHEE6sFmXl2k/8Mil2rh0gaL1TDjKOZo7abGM+p5HPMvgQBWHq8spbTVtOoKfn6r4RgO+fIPPrseFxi2ZbuolcrHKu+tmjVvOdZ4+Y4dbQ6WzN1zlB0Fp3AnJx/JnnhOWOuK9ozsciQnNX2NmzK3pWM2gfQd5BRXmJfLL82MSZOuyJDaJd82ju1r9pYv931O1hHrdPpb9cglVA6JzkCWondg5K2FI9MtNSbQX/Pig+0FFMO7JMsnSEkYqx1bTQe2Z8wxbOJnb7u1vg/7trPPTYn8mp5hlc3S5XcxyG05JaaBZ/io='
#  artifacts:
#    paths:
#    - ./.artifacts.zip

git:
  depth: false

env:
  global:
  - GRADLE_OPTS="-Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.io.useCanonCaches=false -Djava.awt.headless=true"

before_cache:
- rm -rf $HOME/.gradle/daemon $HOME/.gradle/build-scan-data $HOME/.gradle/kotlin-profile $HOME/.gradle/tmp $HOME/.gradle/workers
- find $HOME/.gradle -name '*.lock' -type f -delete

cache:
  directories:
  - $HOME/.gradle/
  - $HOME/.sonar/cache

before_script:
- sed -i 's/-all\.zip/-bin.zip/' ./gradle/wrapper/gradle-wrapper.properties

script:
- ./.travis/build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh
  on:
    tags: true
