# Configuration file for Mergify GitHub App: https://github.com/marketplace/mergify

# All Status Checks should be listed explicitly (see https://doc.mergify.io/conditions.html#validating-all-status-check):
#   `Travis CI - Branch` - https://github.com/marketplace/travis-ci
#   `Travis CI - Pull Request` - https://github.com/marketplace/travis-ci
#   `SonarCloud Code Analysis` - https://sonarcloud.io/documentation/integrations/github/
#   `CodeFactor` - https://github.com/marketplace/codefactor
#   `WIP` - https://github.com/marketplace/wip

pull_request_rules:
- name: Auto merge approved
  conditions:
  - "#approved-reviews-by>=1"
  - -closed
  - -merged
  - -conflict
  - -draft
  - -locked
  - "#changes-requested-reviews-by=0"
  - status-success=Travis CI - Pull Request
  - status-success=SonarCloud Code Analysis
  - status-success=CodeFactor
  - status-success=WIP
  - '#status-neutral=0'
  - '#status-failure=0'
  actions:
    merge:
      method: squash
      strict: smart+fasttrack

- name: Auto approve dependencies
  conditions:
  - author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - -status-neutral=renovate/stability-days
  - -status-failure=renovate/stability-days
  - -closed
  - -merged
  actions:
    review: { }

- name: Update all PRs to master
  conditions:
  - base=master
  - "#approved-reviews-by=0"
  - -author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - -closed
  - -merged
  - -conflict
  - -locked
  actions:
    update: { }

- name: Auto merge by authors
  conditions:
  - author=remal
  - -closed
  - -merged
  - -conflict
  - -draft
  - -locked
  - "#changes-requested-reviews-by=0"
  - status-success=Travis CI - Pull Request
  - status-success=SonarCloud Code Analysis
  - status-success=CodeFactor
  - status-success=WIP
  - '#status-neutral=0'
  - '#status-failure=0'
  actions:
    review: { }
    merge:
      method: squash
      strict: smart+fasttrack
