# Configuration file for Mergify GitHub App: https://github.com/marketplace/mergify

# All Status Checks should be listed explicitly (see https://docs.mergify.io/conditions/#about-status-checks):
#   `build` - .github/workflows/build.yml
#   `SonarCloud Code Analysis` - https://sonarcloud.io/documentation/integrations/github/
#   `WIP` - https://github.com/marketplace/wip

pull_request_rules:
- name: Auto merge approved
  conditions:
  - '#approved-reviews-by>=1'
  - -conflict
  - -closed
  - -merged
  - -draft
  - -locked
  - '#changes-requested-reviews-by=0'
  - check-success=build
  - check-success=SonarCloud Code Analysis
  - check-success=WIP
  - '#check-pending=0'
  - '#check-neutral=0'
  - '#check-failure=0'
  actions:
    merge:
      method: squash
      strict: smart+fasttrack

- name: Auto approve dependency updates
  conditions:
  - author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - label!=dependencies-ci
  - label!=sync-with-template
  - 'check-neutral!=renovate/stability-days'
  - 'check-pending!=renovate/stability-days'
  - 'check-failure!=renovate/stability-days'
  - -closed
  - -merged
  actions:
    review: { }

- name: Merge by authors automatically
  conditions:
  - author=remal
  - label!=dependencies-ci
  - label!=sync-with-template
  - -conflict
  - -closed
  - -merged
  - -draft
  - -locked
  - '#changes-requested-reviews-by=0'
  - check-success=build
  - check-success=SonarCloud Code Analysis
  - check-success=WIP
  - '#check-pending=0'
  - '#check-neutral=0'
  - '#check-failure=0'
  actions:
    review: { }
    merge:
      method: squash
      strict: smart+fasttrack
