# Configuration file for Mergify GitHub App: https://github.com/marketplace/mergify

# All Status Checks should be listed explicitly (see https://doc.mergify.io/conditions.html#validating-all-status-check):
#   `build` - .github/workflows/build.yml
#   `SonarCloud Code Analysis` - https://sonarcloud.io/documentation/integrations/github/
#   `WIP` - https://github.com/marketplace/wip

pull_request_rules:
- name: Auto merge approved
  conditions:
  - "#approved-reviews-by>=1"
  - -conflict
  - -closed
  - -merged
  - -draft
  - -locked
  - "#changes-requested-reviews-by=0"
  - status-success=build
  - status-success=SonarCloud Code Analysis
  - status-success=WIP
  - '#status-neutral=0'
  - '#status-failure=0'
  actions:
    merge:
      method: squash
      strict: smart+fasttrack

- name: Auto approve dependencies
  conditions:
  - author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - label!=dependencies-ci
  - label!=sync-with-template
  - -closed
  - -merged
  actions:
    review:
      message: 'Approved automatically by @Mergifyio.'

- name: Update all PRs to master
  conditions:
  - base=master
  - "#approved-reviews-by=0"
  - -author~=^(dependabot(-preview)?|renovate)\[bot\]$
  - -conflict
  - -closed
  - -merged
  - -locked
  actions:
    update: {}

- name: Merge by authors automatically
  conditions:
  - author=remal
  - label!=dependencies-ci
  - label!=sync-with-template
  - -conflict
  - -closed
  - -merged
  - -draft
  - -locked
  - "#changes-requested-reviews-by=0"
  - status-success=build
  - status-success=SonarCloud Code Analysis
  - status-success=WIP
  - '#status-neutral=0'
  - '#status-failure=0'
  actions:
    review: { }
    merge:
      method: squash
      strict: smart+fasttrack
