# Configuration file for Mergify GitHub App: https://github.com/marketplace/mergify

# All Status Checks should be listed explicitly (see https://doc.mergify.io/conditions.html#validating-all-status-check):
#   `Travis CI - Branch` - https://github.com/marketplace/travis-ci
#   `Travis CI - Pull Request` - https://github.com/marketplace/travis-ci
#   `CodeFactor` - https://github.com/marketplace/codefactor
#   `WIP` - https://github.com/marketplace/wip

pull_request_rules:
  - name: Auto merge approved
    conditions:
      - "#approved-reviews-by>=1"
      - -conflict
      - -draft
      - -locked
      - "#changes-requested-reviews-by=0"
      - status-success=Travis CI - Pull Request
      - status-success=CodeFactor
      - status-success=WIP
      - '#status-neutral=0'
      - '#status-failure=0'
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
      #backport: {}
      delete_head_branch: {}

  - name: Auto merge dependencies
    conditions:
      - author~=^(dependabot(-preview)?|renovate)\[bot\]$
      - status-success=Travis CI - Pull Request
      - '#status-neutral=0'
      - '#status-failure=0'
    actions:
      review: {}
      merge:
        method: squash
        strict: smart+fasttrack
      #backport: {}
      delete_head_branch: {}
