spring:
  kafka:
    clientId: ${spring.application.name}
    consumer:
      group-id: ${spring.application.name}
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      batch-size: 0
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    loadbalancer:
      cache:
        enabled: false

logging:
  level:
    org.apache.kafka: ERROR
    org.jboss.threads: WARN
    org.xnio: WARN
    org.springframework.context.support: WARN
    org.springframework.cloud.loadbalancer.core.ServiceInstanceListSupplierBuilder: ERROR

tracingspec:
  retriever:
    zipkin:
      connect-timeout-millis: 1000
      write-timeout-millis: 1000
      read-timeout-millis: 5000
    jaeger:
      timeout-millis: 10000

  renderer:
    options:
      graph-processors:
      - replace-single-root-with-children
      node-processors:
      - append-server-to-client
      - set-kafka-remote-service-name-from-tag
      tags-to-display:
      - kafka.topic
