@startuml
[-> A: parent
activate A
  A -> B
  activate B
    B -> C: child1
    activate C
    return <size:9>child1</size>
    B -> D: child2
    activate D
    return <size:9>child2</size>
  return
return <size:9>parent</size>
@enduml
