# This file is handled by Dependabot and Renovate bots,
# so we'll run integration tests when a new Zipkin version is released
FROM openzipkin/zipkin:2.22.0@sha256:0c9b8f44d4dca789e0dabd2ba5b995271e6be38fb1db4a391d6fec913c53bae9
