# This file is handled by Dependabot and Renovate bots,
# so we'll run integration tests when a new Zipkin version is released
FROM openzipkin/zipkin:2.21.5@sha256:096200b68b0c56ab3446622a94c8d1a64c849b36d068c3bcf0799c73435d2e48
