# This file is handled by Dependabot and Renovate bots,
# so we'll run integration tests when a new Zipkin version is released
FROM openzipkin/zipkin:2.22.0@sha256:e7c6990921cde0fd968e303368292da1f54695000011f7d1dc1dc7f8fb8294f7
