name: build

on:
  push:
    branches:
    - master
    tags:
    - ver-*
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 2

    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build
      run: |
        chmod -R 0777 .
        ./gradlew allClasses
        export DISABLE_COMPILATION=true

      # ./gradlew build

    - name: Analyze with SonarQube
      run: |
        ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.organization=remal
      env:
        DISABLE_COMPILATION: true

    #    - name: Run full test suit
    #      run: |
    #        ./gradlew runAllTests
    #      env:
    #        DISABLE_COMPILATION: true

    - name: Push back
      if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/') }}
      run: |
        git remote set-url origin https://${{ secrets.PUSH_BACK_TOKEN }}@github.com/${{ github.repository }}

        git add --all .idea
        git commit --no-status -o -m "[push-back] Update IDEA settings" .idea && git push origin "HEAD:${{ github.ref }}"

        git add --all README.md example-graph.png
        git commit --no-status -o -m "[push-back] Update documentation" README.md example-graph.png && git push origin "HEAD:${{ github.ref }}"
