name: build

on:
  push:
    branches:
    - master
    tags:
    - ver-*
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 2

    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile
      run: |
        chmod -R 0777 .
        ./gradlew allClasses
        echo "DISABLE_COMPILATION=true" >> "$GITHUB_ENV"

    - name: Build
      run: |
        ./gradlew build

    - name: Analyze with SonarQube
      run: |
        ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.organization=remal
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #    - name: Run full test suit
    #      if: ${{ github.event_name != 'pull_request' || github.event.pull_request.sender.login != 'renovate[bot]' }}
    #      run: |
    #        ./gradlew runAllTests
    #      env:
    #        DISABLE_COMPILATION: true

    - name: 'Run full test suit: integration.versions-count=3'
      if: ${{ github.event_name == 'pull_request' && github.event.pull_request.sender.login == 'renovate[bot]' }}
      run: |
        ./gradlew runAllTests -Dintegration.versions-count=3

    - name: Push back
      if: ${{ github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/') }}
      run: |
        git remote add push-back https://${{ secrets.PUSH_BACK_TOKEN }}@github.com/${{ github.repository }}
        git config user.name "${{ github.event.head_commit.committer.name }}"
        git config user.email "${{ github.event.head_commit.committer.email }}"

        echo "::group::Update IDEA settings"
        git add --all .idea
        if git commit --no-status -o -m "[push-back] Update IDEA settings" .idea ; then
          git push push-back "HEAD:${{ github.ref }}"
        fi
        echo "::endgroup::"

        echo "::group::Update documentation"
        git add --all README.md example-graph.png
        if git commit --no-status -o -m "[push-back] Update documentation" README.md example-graph.png ; then
          git push push-back "HEAD:${{ github.ref }}"
        fi
        echo "::endgroup::"
