name: build

on:
  push:
    branches:
    - main
    tags:
    - ver-*
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

    steps:
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11


    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 0

    - name: Adjust files to be built on CI
      run: |
        sed -i 's/-all\.zip/-bin.zip/' gradle/wrapper/gradle-wrapper.properties


    - name: Create cache key
      id: create-cache-key
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: echo "::set-output name=year-month::$(date '+%Y.%m')"

    - name: Cache
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/cache@v2
      with:
        key: ${{ steps.create-cache-key.outputs.year-month }}-${{ runner.os }}-${{ github.ref }}
        restore-keys: |
          ${{ steps.create-cache-key.outputs.year-month }}-${{ runner.os }}-${{ github.ref }}
          ${{ steps.create-cache-key.outputs.year-month }}-${{ runner.os }}-refs/heads/master
        path: |
          ~/.gradle
          ~/.sonar/cache


    - name: Compile
      run: |
        chmod -R 0777 .
        ./gradlew allClasses
        echo "DISABLE_COMPILATION=true" >> "$GITHUB_ENV"

    - name: Build
      run: |
        ./gradlew build runAllTests


    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
      if: ${{ env.PUSH_BACK_TOKEN && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
      run: |
        REMOTE_URL=$(git config --get remote.origin.url)
        REMOTE_HEAD_COMMIT_SHA=$(git ls-remote "$REMOTE_URL" "${{ github.ref }}" | awk '{ print $1}')
        if [ "$REMOTE_HEAD_COMMIT_SHA" != "${{ github.sha }}" ]; then
          echo "::warning::Remote repository branch has been changed, skipping push back"
          exit 0
        fi

        git config --unset-all "http.https://github.com/.extraheader"
        git remote set-url origin https://${{ env.PUSH_BACK_TOKEN }}@github.com/${{ github.repository }}
        git config user.name "${{ github.event.head_commit.committer.name }}"
        git config user.email "${{ github.event.head_commit.committer.email }}"

        echo "::group::IDEA settings"
        git add --all .idea
        if git commit --quiet --no-status --no-edit --only -m "[push-back] Update IDEA settings" .idea ; then
          git push origin "HEAD:${{ github.ref }}"
        fi
        echo "::endgroup::"


    - name: Remove files that shouldn't be cached
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        rm -rf $HOME/.gradle/daemon $HOME/.gradle/build-scan-data $HOME/.gradle/kotlin-profile $HOME/.gradle/tmp $HOME/.gradle/workers || true
        find $HOME/.gradle -name '*.lock' -type f -delete
