name: ci

on:
  push:
    branches:
    - master
    tags:
    - ver-*
  #pull_request: { }
  pull_request_target: { }

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[push-back]') && !startsWith(github.event.head_commit.message, '[skip ci]'))
      || github.event_name != 'push'
      }}
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 2

    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
