name: 'Codeowners validation'

on:
  push:
    paths:
    - '.github/CODEOWNERS'
    - '.github/workflows/codeowners-validator.yml'
    branches:
    - '**'
    tags-ignore:
    - '**'
  schedule:
  - cron: '37 4 * * *'
  workflow_dispatch: { }

jobs:
  codeowners-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2
      with:
        fetch-depth: 1

    - name: Get repository owner type
      id: owner-type
      run: |
        REPO_JSON=$(curl -s "${{ github.api_url}}/repos/${{ github.repository	}}" -H "Authorization: token ${{ github.token }}")
        OWNER_TYPE=$(echo $REPO_JSON | jq -r '.owner.type')
        OWNER_TYPE=$(echo "$OWNER_TYPE" | tr '[:upper:]' '[:lower:]')
        echo "Owner type: $OWNER_TYPE"
        echo "::set-output name=owner-type::$OWNER_TYPE"

    - name: Basic CODEOWNERS validation
      if: ${{ steps.owner-type.outputs.owner-type != 'organization' }}
      uses: mszostok/codeowners-validator@2f6e3bb39aa6837d7dcf8eff2de5d6c046d0c9a9 # tag=v0.6.0
      with:
        checks: 'syntax,duppatterns,files'
        github_access_token: '${{ github.token }}'

    - name: Full CODEOWNERS validation
      if: ${{ steps.owner-type.outputs.owner-type == 'organization' }}
      uses: mszostok/codeowners-validator@2f6e3bb39aa6837d7dcf8eff2de5d6c046d0c9a9 # tag=v0.6.0
      with:
        github_access_token: '${{ github.token }}'
