name: Sync with template repository

on:
  schedule:
  - cron: '47 * * * *'
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}

jobs:
  sync-with-template:
    name: Sync with template repository
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Sync with template repository
      uses: remal-github-actions/sync-with-template@v1
      if: ${{ env.PUSH_BACK_TOKEN }}
      with:
        githubToken: '${{ env.PUSH_BACK_TOKEN }}'
        templateRepository: '${{ secrets.TEMPLATE_REPOSITORY }}'
