name: Sync with template repository

on:
  schedule:
  - cron: '47 * * * *'
  workflow_dispatch:
    inputs:
      debug:
        required: false
        description: Set to 'true' to enable debug logs

defaults:
  run:
    shell: bash

env:
  PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
  ACTIONS_STEP_DEBUG: ${{ github.event.inputs.debug }}

jobs:
  sync-with-template:
    name: Sync with template repository
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Sync with template repository
      uses: remal-github-actions/sync-with-template@85a3efd3af3e7e1ad2d00603bc057ab7224d8097 # renovate: tag=v1
      if: ${{ env.PUSH_BACK_TOKEN }}
      with:
        githubToken: '${{ env.PUSH_BACK_TOKEN }}'
        templateRepository: '${{ secrets.TEMPLATE_REPOSITORY }}'
